$main_monitor = DP-3
$second_monitor = DP-1

$blur_passes = 0
$background_color = rgba(0, 0, 0, 0.5)

general {
    hide_cursor = true
    no_fade_out = false
    no_fade_in = false
}

background {
    monitor = $main_monitor
    path = ~/.config/wallpapers/rimuru_blue.png
    color = $background_color
    blur_passes = $blur_passes
    noise = 0.0
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

# INPUT FIELD
input-field {
    monitor = $main_monitor
    size = 250, 60
    outline_thickness = 2
    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.2 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    outer_color = rgba(0, 0, 0, 0)
    inner_color = rgba(0, 0, 0, 0.5)
    font_color = rgb(200, 200, 200)
    fade_on_empty = false
    font_family = JetBrains Mono Nerd Font Mono
    placeholder_text = <i><span foreground="##cdd6f4">Input Password...</span></i>
    hide_input = false
    position = 0, -120
    halign = center
    valign = center
}

label {
    monitor = $main_monitor
    text = cmd[update:1000] echo "$(date +"%-I:%M%p")"
    color = rgba(227, 187, 166, 1)
    font_size = 120
    font_family = JetBrains Mono Nerd Font Mono ExtraBold
    position = 50, -10
    halign = left
    valign = top
}

# second monitor

background {
    monitor = $second_monitor
    path = ~/.config/wallpapers/rudeus_vertical.png
    color = $background_color
    blur_passes = $blur_passes
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}