# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/cd7d5c99-1da0-4778-bcff-32d7819f3c8b";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/053C-BAAE";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/mnt/mysqldata" =
    { device = "/dev/disk/by-uuid/3d7f2e6f-e9fb-4228-bea8-1d32d2dc00a2";
      fsType = "ext4";
    };

  fileSystems."/mnt/other1" =
    { device = "/dev/disk/by-uuid/9c915ced-42b9-4b1c-8a35-81e56c69db1e";
      fsType = "ext4";
    };

  fileSystems."/mnt/nextcould-data" =
    { device = "/dev/disk/by-uuid/c777cae5-5576-42a3-86c6-88466fa8dafe";
      fsType = "ext4";
    };

  fileSystems."/mnt/jellyfin-data" =
    { device = "/dev/disk/by-uuid/14a5d96b-edf5-4ee7-94d7-6b8ce7e16eec";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/456dd15d-b9f5-42dc-92ff-482d0346281f"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp3s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
